categories:
  Wearable Gadgets:
    Smart Watches: https://www.ishopping.pk/electronics/wearable-gadgets/smart-watches.html
    VR Glasses: https://www.ishopping.pk/electronics/wearable-gadgets/vr-glasses.html
    Smart Band: https://www.ishopping.pk/electronics/wearable-gadgets/smart-band.html
    Smart Item Tracker: https://www.ishopping.pk/electronics/wearable-gadgets/smart-item-tracker.html
    Smart Watches Accessories: https://www.ishopping.pk/electronics/wearable-gadgets/smart-watches-accessories.html
    Earbuds: https://www.ishopping.pk/electronics/wearable-gadgets/earbuds.html
  Men's Clothing:
    Mens Casual Wear: https://www.ishopping.pk/mens-store/men-s-clothing/casual-wear-for-men.html
    Men's T-Shirts: https://www.ishopping.pk/mens-store/men-s-clothing/casual-wear-for-men/mens-t-shirts.html
    Men's Jeans: https://www.ishopping.pk/mens-store/men-s-clothing/casual-wear-for-men/mens-jeans.html
  Men's Footwear:
    Men's Casual-Shoes: https://www.ishopping.pk/mens-store/men-s-footwear/casual-shoes.html
    Men's Formal-Shoes: https://www.ishopping.pk/mens-store/men-s-footwear/formal-shoes.html
    Men's Sneakers: https://www.ishopping.pk/mens-store/men-s-footwear/mens-sneakers.html
  Women's Clothing:
    Women's Winter-Wear: https://www.ishopping.pk/women-s-store/women-s-clothing/winter-wear-for-women.html
    Women's Summer-Wear: https://www.ishopping.pk/women-s-store/women-s-clothing/summer-clothes-for-women.html
    Women's Western-Clothing: https://www.ishopping.pk/women-s-store/women-s-clothing/western-wear-for-women.html
    Women's Pakistani-Clothing: https://www.ishopping.pk/women-s-store/women-s-clothing/pakistani-clothing-for-women.html
  Women's Footwear:
    Women's Flat&Sandals: https://www.ishopping.pk/women-s-store/women-shoes/ladies-sandals-and-flats.html
    Women's Heels: https://www.ishopping.pk/women-s-store/women-shoes/heels.html
  Computers:
    Laptops: https://www.ishopping.pk/electronics/laptops-computers/laptop.html
    Desktops & Work-Stations: https://www.ishopping.pk/electronics/laptops-computers/desktop.html
  Mobile Accessories:
    All Mobile Accessories: https://www.ishopping.pk/catalog/category/view/s/mobilephone-accessories-price-in-pakistan/id/156/
  Mobiles:
    All Mobiles: https://www.ishopping.pk/electronics/mobile-phones-tablet-pc/mobile-phones-prices-in-pakistan.html
  Tablets:
    All Tablets: https://www.ishopping.pk/mobile-phones-tablet-pc/tablet-pc-price-in-pakistan.html
  LED-TV:
    LED-TV: https://www.ishopping.pk/electronics/tv-s-and-entertainment/led-tv.html
    Smart-LED-TV: https://www.ishopping.pk/electronics/tv-s-and-entertainment/smart-led.html
    Curved-LED-TV: https://www.ishopping.pk/electronics/tv-s-and-entertainment/curved-led.html
    TV-Accessories: https://www.ishopping.pk/electronics/tv-s-and-entertainment/accessories.html
  Home Appliances:
    Air-Conditioners: https://www.ishopping.pk/home-living/home-appliances/air-conditioners.html
    Generators: https://www.ishopping.pk/home-living/home-appliances/generators.html
    Heater: https://www.ishopping.pk/home-living/home-appliances/heater.html
    Vacuum Cleaner: https://www.ishopping.pk/home-living/home-appliances/vacuum-cleaners.html
    Washing Machines: https://www.ishopping.pk/home-living/home-appliances/washing-machines.html
    Household-Fans: https://www.ishopping.pk/home-living/home-appliances/household-fans.html
    Purifiers and Humidifiers: https://www.ishopping.pk/home-living/home-appliances/humidifiers-purifiers.html
    Irons & Steamers: https://www.ishopping.pk/home-living/home-appliances/irons-steamers.html
    Water Dispenser: https://www.ishopping.pk/home-living/home-appliances/water-dispenser.html
    Refrigerators: https://www.ishopping.pk/home-living/home-appliances/refrigerators.html
    Freezers: https://www.ishopping.pk/home-living/home-appliances/freezers.html
    Insect Killer: https://www.ishopping.pk/home-living/home-appliances/insect-killer.html
    Geysers: https://www.ishopping.pk/home-living/home-appliances/geysers.html
    Sewing Machine: https://www.ishopping.pk/home-living/home-appliances/sewing-machine.html
