categories:
  Home Appliances:
    Air-Conditioners: https://www.shophive.com/appliances/air-conditioners
    Purifiers and Humidifiers: https://www.shophive.com/appliances/home/air-purifiers
    Washing Machines: https://www.shophive.com/appliances/home/washing-machine
    Vacuum Cleaner: https://www.shophive.com/appliances/home/vacuum-cleaners
    Heater: https://www.shophive.com/appliances/home/heaters
    Cleaner & Washer: https://www.shophive.com/appliances/home/cleaner-washer
    Geysers: https://www.shophive.com/appliances/home/water-geyser
    Home Automation: https://www.shophive.com/appliances/home/home-automation
    Water Dispenser: https://www.shophive.com/appliances/home/water-cooler
    Houseland-Fans: https://www.shophive.com/appliances/home/fans
  Mobiles:
    Samsung: https://www.shophive.com/mobile-phones/samsung
    Xiaomi: https://www.shophive.com/mobile-phones/xiaomi-mi
    Vivo: https://www.shophive.com/mobile-phones/vivo
    Infinix: https://www.shophive.com/mobile-phones/infinix
    Oppo: https://www.shophive.com/mobile-phones/oppo
    Honor: https://www.shophive.com/mobile-phones/honor
    Realme: https://www.shophive.com/mobile-phones/realme
    Tecno: https://www.shophive.com/mobile-phones/tecno
    Nokia: https://www.shophive.com/mobile-phones/nokia
    Iphone: https://www.shophive.com/apple/iphone
  Mobile Accessories:
    Covers & Cases: https://www.shophive.com/mobile-phones/mobile-accessories/mobiles-tablets-covers-cases
    Screen Protectors: https://www.shophive.com/mobile-phones/mobile-accessories/mobile-screen-protectors-tablets
    Power Bank: https://www.shophive.com/mobile-phones/mobile-accessories/power-bank
    watch: https://www.shophive.com/apple/watch
    airpod: https://www.shophive.com/apple/airpod
    Cables: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/cables
    Wireless QI Chargers: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/wirless-qi-chargers
    Micro USB Cables: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/micro-usb-cables
    Wall Chargers: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/wall-chargers
    Car Chargers: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/car-chargers
    USB Type-C Cables: https://www.shophive.com/mobile-phones/mobile-accessories/chargers/usb-type-c-cables
  Tablets:
    Samsung: https://www.shophive.com/tablets/samsung
    IPad: https://www.shophive.com/apple/ipad
    Xiaomi Mi: https://www.shophive.com/tablets/xiaomi-mi
    Amazon Fire: https://www.shophive.com/tablets/amazon-fire
    XP-Pen: https://www.shophive.com/tablets/xp-pen
    Tablet-Accessories: https://www.shophive.com/tablets/tablet-accessories
  Wearable Gadgets:
    Apple Smartwatch: https://www.shophive.com/apple/watch
    Samsung Smartwatch: https://www.shophive.com/smart-watches/samsung
    Xiaomi Smartwatch: https://www.shophive.com/smart-watches/xiaomi
    Huawei Smartwatch: https://www.shophive.com/smart-watches/huawei
    Realme Smartwatch: https://www.shophive.com/smart-watches/realme
    Amazfit Smartwatch: https://www.shophive.com/smart-watches/amazfit
  Computers:
    Laptops: https://www.shophive.com/laptops-computers/laptops
    Desktops & Work-Stations: https://www.shophive.com/laptops-computers/computers
    Computer Accessories: https://www.shophive.com/laptops-computers/laptop-accessories
