categories:
  Smart Watches:
    Smart Watches: https://www.daraz.pk/smart-watches/
  Mobile Phones:
    Smartphones: https://www.daraz.pk/smartphones/
  Tablets:
    Tablets: https://www.daraz.pk/tablets/
  Home Appliances:
    Air Conditioners: https://www.daraz.pk/air-conditioners/
    Vacuum Cleaners: https://www.daraz.pk/vacuum-cleaners/
  Fragrances:
    Men Perfumes: https://www.daraz.pk/mens-fragrance/
